const fs = require('fs');
const path = require('path');

const rankingsFilePath = path.join(__dirname, '../frontend/src/data/pokemonRankings.ts');
let content = fs.readFileSync(rankingsFilePath, 'utf8');

const startMarker = 'export const pokemonRankings: PokemonRankData[] =';
const nextFnMarker = 'export function getPokemonByIdOrSlug';

const startIndex = content.indexOf(startMarker);
const nextFnIndex = content.indexOf(nextFnMarker, startIndex);

if (startIndex === -1 || nextFnIndex === -1) {
  console.error('Could not locate start/nextFn markers for pokemonRankings');
  process.exit(1);
}

const slice = content.substring(startIndex, nextFnIndex);
const equalSign = slice.indexOf('=');
const arrayStart = slice.indexOf('[', equalSign);
const arrayEnd = slice.lastIndexOf(']');

if (arrayStart === -1 || arrayEnd === -1) {
  console.error('Could not find [ and ] in slice');
  process.exit(1);
}

const jsonStr = slice.substring(arrayStart, arrayEnd + 1);
const list = JSON.parse(jsonStr);
console.log('Original count:', list.length);

// Map of existing items by name
const existingMap = new Map();
list.forEach(p => existingMap.set(p.name, p));

// Comprehensive List of All Megas, Primals, Shadows, and Legends
const allMegasAndShadows = [
  // MEGAS & PRIMALS
  {
    name: "Mega Rayquaza",
    pokedexId: 384,
    types: ["Dragon", "Flying"],
    attack: 377,
    defense: 210,
    stamina: 227,
    maxCp: 6492,
    pveScore: 100,
    dps: 60.5,
    bestFastMove: { name: "Dragon Tail", type: "Dragon" },
    bestChargedMove: { name: "Dragon Ascent", type: "Flying" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Mewtwo X",
    pokedexId: 150,
    types: ["Psychic", "Fighting"],
    attack: 399,
    defense: 215,
    stamina: 228,
    maxCp: 6116,
    pveScore: 98,
    dps: 56.4,
    bestFastMove: { name: "Psycho Cut", type: "Psychic" },
    bestChargedMove: { name: "Psystrike", type: "Psychic" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Mewtwo Y",
    pokedexId: 150,
    types: ["Psychic"],
    attack: 413,
    defense: 223,
    stamina: 228,
    maxCp: 6418,
    pveScore: 100,
    dps: 58.2,
    bestFastMove: { name: "Psycho Cut", type: "Psychic" },
    bestChargedMove: { name: "Psystrike", type: "Psychic" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Charizard X",
    pokedexId: 6,
    types: ["Fire", "Dragon"],
    attack: 273,
    defense: 213,
    stamina: 186,
    maxCp: 4420,
    pveScore: 78,
    dps: 44.5,
    bestFastMove: { name: "Fire Spin", type: "Fire" },
    bestChargedMove: { name: "Blast Burn", type: "Fire" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Charizard Y",
    pokedexId: 6,
    types: ["Fire", "Flying"],
    attack: 319,
    defense: 212,
    stamina: 186,
    maxCp: 5037,
    pveScore: 93,
    dps: 54.8,
    bestFastMove: { name: "Fire Spin", type: "Fire" },
    bestChargedMove: { name: "Blast Burn", type: "Fire" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Venusaur",
    pokedexId: 3,
    types: ["Grass", "Poison"],
    attack: 241,
    defense: 246,
    stamina: 190,
    maxCp: 4181,
    pveScore: 82,
    dps: 45.1,
    bestFastMove: { name: "Vine Whip", type: "Grass" },
    bestChargedMove: { name: "Frenzy Plant", type: "Grass" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Blastoise",
    pokedexId: 9,
    types: ["Water"],
    attack: 264,
    defense: 237,
    stamina: 188,
    maxCp: 4455,
    pveScore: 84,
    dps: 46.8,
    bestFastMove: { name: "Water Gun", type: "Water" },
    bestChargedMove: { name: "Hydro Cannon", type: "Water" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Gengar",
    pokedexId: 94,
    types: ["Ghost", "Poison"],
    attack: 349,
    defense: 199,
    stamina: 155,
    maxCp: 4902,
    pveScore: 92,
    dps: 54.2,
    bestFastMove: { name: "Lick", type: "Ghost" },
    bestChargedMove: { name: "Shadow Ball", type: "Ghost" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Alakazam",
    pokedexId: 65,
    types: ["Psychic"],
    attack: 367,
    defense: 193,
    stamina: 146,
    maxCp: 5063,
    pveScore: 91,
    dps: 53.7,
    bestFastMove: { name: "Confusion", type: "Psychic" },
    bestChargedMove: { name: "Psychic", type: "Psychic" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Beedrill",
    pokedexId: 15,
    types: ["Bug", "Poison"],
    attack: 303,
    defense: 148,
    stamina: 163,
    maxCp: 3824,
    pveScore: 78,
    dps: 45.9,
    bestFastMove: { name: "Bug Bite", type: "Bug" },
    bestChargedMove: { name: "X-Scissor", type: "Bug" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Pinsir",
    pokedexId: 127,
    types: ["Bug", "Flying"],
    attack: 305,
    defense: 231,
    stamina: 163,
    maxCp: 4610,
    pveScore: 84,
    dps: 47.6,
    bestFastMove: { name: "Bug Bite", type: "Bug" },
    bestChargedMove: { name: "X-Scissor", type: "Bug" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Scizor",
    pokedexId: 212,
    types: ["Bug", "Steel"],
    attack: 279,
    defense: 250,
    stamina: 172,
    maxCp: 4621,
    pveScore: 83,
    dps: 46.5,
    bestFastMove: { name: "Bullet Punch", type: "Steel" },
    bestChargedMove: { name: "Iron Head", type: "Steel" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 2
  },
  {
    name: "Mega Heracross",
    pokedexId: 214,
    types: ["Bug", "Fighting"],
    attack: 334,
    defense: 223,
    stamina: 190,
    maxCp: 5448,
    pveScore: 93,
    dps: 53.9,
    bestFastMove: { name: "Counter", type: "Fighting" },
    bestChargedMove: { name: "Close Combat", type: "Fighting" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 2
  },
  {
    name: "Mega Houndoom",
    pokedexId: 229,
    types: ["Dark", "Fire"],
    attack: 289,
    defense: 194,
    stamina: 181,
    maxCp: 4344,
    pveScore: 82,
    dps: 46.1,
    bestFastMove: { name: "Fire Fang", type: "Fire" },
    bestChargedMove: { name: "Foul Play", type: "Dark" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 2
  },
  {
    name: "Mega Sceptile",
    pokedexId: 254,
    types: ["Grass", "Dragon"],
    attack: 320,
    defense: 186,
    stamina: 172,
    maxCp: 4598,
    pveScore: 91,
    dps: 54.1,
    bestFastMove: { name: "Bullet Seed", type: "Grass" },
    bestChargedMove: { name: "Frenzy Plant", type: "Grass" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Blaziken",
    pokedexId: 257,
    types: ["Fire", "Fighting"],
    attack: 329,
    defense: 168,
    stamina: 190,
    maxCp: 4704,
    pveScore: 93,
    dps: 55.4,
    bestFastMove: { name: "Fire Spin", type: "Fire" },
    bestChargedMove: { name: "Blast Burn", type: "Fire" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Swampert",
    pokedexId: 260,
    types: ["Water", "Ground"],
    attack: 283,
    defense: 218,
    stamina: 225,
    maxCp: 4975,
    pveScore: 92,
    dps: 52.8,
    bestFastMove: { name: "Water Gun", type: "Water" },
    bestChargedMove: { name: "Hydro Cannon", type: "Water" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Gardevoir",
    pokedexId: 282,
    types: ["Psychic", "Fairy"],
    attack: 326,
    defense: 229,
    stamina: 169,
    maxCp: 5101,
    pveScore: 91,
    dps: 52.3,
    bestFastMove: { name: "Charm", type: "Fairy" },
    bestChargedMove: { name: "Dazzling Gleam", type: "Fairy" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Gallade",
    pokedexId: 475,
    types: ["Psychic", "Fighting"],
    attack: 326,
    defense: 199,
    stamina: 169,
    maxCp: 4894,
    pveScore: 81,
    dps: 45.2,
    bestFastMove: { name: "Low Kick", type: "Fighting" },
    bestChargedMove: { name: "Close Combat", type: "Fighting" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Mega Banette",
    pokedexId: 354,
    types: ["Ghost"],
    attack: 312,
    defense: 160,
    stamina: 162,
    maxCp: 4094,
    pveScore: 84,
    dps: 50.1,
    bestFastMove: { name: "Shadow Claw", type: "Ghost" },
    bestChargedMove: { name: "Shadow Ball", type: "Ghost" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Glalie",
    pokedexId: 362,
    types: ["Ice"],
    attack: 252,
    defense: 190,
    stamina: 190,
    maxCp: 3681,
    pveScore: 78,
    dps: 43.8,
    bestFastMove: { name: "Frost Breath", type: "Ice" },
    bestChargedMove: { name: "Avalanche", type: "Ice" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Abomasnow",
    pokedexId: 460,
    types: ["Grass", "Ice"],
    attack: 240,
    defense: 191,
    stamina: 207,
    maxCp: 3848,
    pveScore: 79,
    dps: 43.1,
    bestFastMove: { name: "Powder Snow", type: "Ice" },
    bestChargedMove: { name: "Weather Ball", type: "Ice" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Mega Lucario",
    pokedexId: 448,
    types: ["Fighting", "Steel"],
    attack: 310,
    defense: 175,
    stamina: 172,
    maxCp: 4325,
    pveScore: 94,
    dps: 55.7,
    bestFastMove: { name: "Force Palm", type: "Fighting" },
    bestChargedMove: { name: "Aura Sphere", type: "Fighting" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Mega Garchomp",
    pokedexId: 445,
    types: ["Dragon", "Ground"],
    attack: 339,
    defense: 222,
    stamina: 239,
    maxCp: 6109,
    pveScore: 96,
    dps: 56.8,
    bestFastMove: { name: "Dragon Tail", type: "Dragon" },
    bestChargedMove: { name: "Outrage", type: "Dragon" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Mega Tyranitar",
    pokedexId: 248,
    types: ["Rock", "Dark"],
    attack: 309,
    defense: 276,
    stamina: 225,
    maxCp: 6045,
    pveScore: 95,
    dps: 55.2,
    bestFastMove: { name: "Bite", type: "Dark" },
    bestChargedMove: { name: "Brutal Swing", type: "Dark" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 2
  },
  {
    name: "Mega Salamence",
    pokedexId: 373,
    types: ["Dragon", "Flying"],
    attack: 310,
    defense: 251,
    stamina: 216,
    maxCp: 5688,
    pveScore: 93,
    dps: 53.6,
    bestFastMove: { name: "Dragon Tail", type: "Dragon" },
    bestChargedMove: { name: "Outrage", type: "Dragon" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Metagross",
    pokedexId: 376,
    types: ["Steel", "Psychic"],
    attack: 300,
    defense: 289,
    stamina: 190,
    maxCp: 5652,
    pveScore: 95,
    dps: 55.6,
    bestFastMove: { name: "Bullet Punch", type: "Steel" },
    bestChargedMove: { name: "Meteor Mash", type: "Steel" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Manectric",
    pokedexId: 310,
    types: ["Electric"],
    attack: 286,
    defense: 179,
    stamina: 172,
    maxCp: 4048,
    pveScore: 84,
    dps: 47.9,
    bestFastMove: { name: "Thunder Fang", type: "Electric" },
    bestChargedMove: { name: "Wild Charge", type: "Electric" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Diancie",
    pokedexId: 719,
    types: ["Rock", "Fairy"],
    attack: 342,
    defense: 235,
    stamina: 137,
    maxCp: 4913,
    pveScore: 93,
    dps: 55.1,
    bestFastMove: { name: "Rock Throw", type: "Rock" },
    bestChargedMove: { name: "Rock Slide", type: "Rock" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 6
  },
  {
    name: "Mega Latios",
    pokedexId: 381,
    types: ["Dragon", "Psychic"],
    attack: 335,
    defense: 241,
    stamina: 190,
    maxCp: 5661,
    pveScore: 94,
    dps: 55.4,
    bestFastMove: { name: "Dragon Breath", type: "Dragon" },
    bestChargedMove: { name: "Dragon Claw", type: "Dragon" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Aerodactyl",
    pokedexId: 142,
    types: ["Rock", "Flying"],
    attack: 292,
    defense: 210,
    stamina: 190,
    maxCp: 4704,
    pveScore: 79,
    dps: 43.8,
    bestFastMove: { name: "Rock Throw", type: "Rock" },
    bestChargedMove: { name: "Rock Slide", type: "Rock" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Ampharos",
    pokedexId: 181,
    types: ["Electric", "Dragon"],
    attack: 294,
    defense: 203,
    stamina: 207,
    maxCp: 4799,
    pveScore: 76,
    dps: 41.5,
    bestFastMove: { name: "Volt Switch", type: "Electric" },
    bestChargedMove: { name: "Zap Cannon", type: "Electric" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 2
  },
  {
    name: "Mega Lopunny",
    pokedexId: 428,
    types: ["Normal", "Fighting"],
    attack: 282,
    defense: 214,
    stamina: 163,
    maxCp: 4234,
    pveScore: 74,
    dps: 40.2,
    bestFastMove: { name: "Double Kick", type: "Fighting" },
    bestChargedMove: { name: "Focus Blast", type: "Fighting" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Mega Altaria",
    pokedexId: 334,
    types: ["Dragon", "Fairy"],
    attack: 222,
    defense: 218,
    stamina: 181,
    maxCp: 3574,
    pveScore: 68,
    dps: 34.6,
    bestFastMove: { name: "Dragon Breath", type: "Dragon" },
    bestChargedMove: { name: "Dazzling Gleam", type: "Fairy" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Latias",
    pokedexId: 380,
    types: ["Dragon", "Psychic"],
    attack: 289,
    defense: 297,
    stamina: 190,
    maxCp: 5428,
    pveScore: 82,
    dps: 44.1,
    bestFastMove: { name: "Dragon Breath", type: "Dragon" },
    bestChargedMove: { name: "Outrage", type: "Dragon" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Sableye",
    pokedexId: 302,
    types: ["Dark", "Ghost"],
    attack: 151,
    defense: 216,
    stamina: 137,
    maxCp: 2196,
    pveScore: 52,
    dps: 22.8,
    bestFastMove: { name: "Shadow Claw", type: "Ghost" },
    bestChargedMove: { name: "Foul Play", type: "Dark" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Mawile",
    pokedexId: 303,
    types: ["Steel", "Fairy"],
    attack: 188,
    defense: 217,
    stamina: 137,
    maxCp: 2694,
    pveScore: 56,
    dps: 26.4,
    bestFastMove: { name: "Fairy Wind", type: "Fairy" },
    bestChargedMove: { name: "Play Rough", type: "Fairy" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Medicham",
    pokedexId: 308,
    types: ["Fighting", "Psychic"],
    attack: 205,
    defense: 179,
    stamina: 155,
    maxCp: 2821,
    pveScore: 58,
    dps: 28.1,
    bestFastMove: { name: "Counter", type: "Fighting" },
    bestChargedMove: { name: "Dynamic Punch", type: "Fighting" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Sharpedo",
    pokedexId: 319,
    types: ["Water", "Dark"],
    attack: 289,
    defense: 144,
    stamina: 172,
    maxCp: 3832,
    pveScore: 75,
    dps: 44.8,
    bestFastMove: { name: "Waterfall", type: "Water" },
    bestChargedMove: { name: "Hydro Pump", type: "Water" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Camerupt",
    pokedexId: 323,
    types: ["Fire", "Ground"],
    attack: 253,
    defense: 179,
    stamina: 172,
    maxCp: 3624,
    pveScore: 71,
    dps: 38.9,
    bestFastMove: { name: "Incinerate", type: "Fire" },
    bestChargedMove: { name: "Overheat", type: "Fire" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Audino",
    pokedexId: 531,
    types: ["Normal", "Fairy"],
    attack: 147,
    defense: 239,
    stamina: 230,
    maxCp: 2854,
    pveScore: 51,
    dps: 21.2,
    bestFastMove: { name: "Pound", type: "Normal" },
    bestChargedMove: { name: "Dazzling Gleam", type: "Fairy" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 5
  },
  {
    name: "Mega Pidgeot",
    pokedexId: 18,
    types: ["Normal", "Flying"],
    attack: 280,
    defense: 175,
    stamina: 195,
    maxCp: 4160,
    pveScore: 78,
    dps: 43.2,
    bestFastMove: { name: "Gust", type: "Flying" },
    bestChargedMove: { name: "Brave Bird", type: "Flying" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Slowbro",
    pokedexId: 80,
    types: ["Water", "Psychic"],
    attack: 224,
    defense: 259,
    stamina: 216,
    maxCp: 4165,
    pveScore: 70,
    dps: 35.8,
    bestFastMove: { name: "Water Gun", type: "Water" },
    bestChargedMove: { name: "Psychic", type: "Psychic" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Steelix",
    pokedexId: 208,
    types: ["Steel", "Ground"],
    attack: 212,
    defense: 327,
    stamina: 181,
    maxCp: 4149,
    pveScore: 73,
    dps: 34.2,
    bestFastMove: { name: "Iron Tail", type: "Steel" },
    bestChargedMove: { name: "Heavy Slam", type: "Steel" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 2
  },
  {
    name: "Mega Aggron",
    pokedexId: 306,
    types: ["Steel"],
    attack: 247,
    defense: 331,
    stamina: 172,
    maxCp: 4762,
    pveScore: 79,
    dps: 39.5,
    bestFastMove: { name: "Iron Tail", type: "Steel" },
    bestChargedMove: { name: "Heavy Slam", type: "Steel" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Mega Gyarados",
    pokedexId: 130,
    types: ["Water", "Dark"],
    attack: 292,
    defense: 247,
    stamina: 216,
    maxCp: 5332,
    pveScore: 84,
    dps: 45.1,
    bestFastMove: { name: "Waterfall", type: "Water" },
    bestChargedMove: { name: "Hydro Pump", type: "Water" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Kangaskhan",
    pokedexId: 115,
    types: ["Normal"],
    attack: 246,
    defense: 210,
    stamina: 233,
    maxCp: 4353,
    pveScore: 72,
    dps: 36.4,
    bestFastMove: { name: "Mud-Slap", type: "Ground" },
    bestChargedMove: { name: "Outrage", type: "Dragon" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Mega Absol",
    pokedexId: 359,
    types: ["Dark"],
    attack: 314,
    defense: 130,
    stamina: 163,
    maxCp: 3770,
    pveScore: 75,
    dps: 46.2,
    bestFastMove: { name: "Snarl", type: "Dark" },
    bestChargedMove: { name: "Dark Pulse", type: "Dark" },
    isMega: true,
    isShadow: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Primal Groudon",
    pokedexId: 383,
    types: ["Ground", "Fire"],
    attack: 353,
    defense: 268,
    stamina: 218,
    maxCp: 6672,
    pveScore: 100,
    dps: 60.1,
    bestFastMove: { name: "Mud Shot", type: "Ground" },
    bestChargedMove: { name: "Precipice Blades", type: "Ground" },
    isMega: false,
    isShadow: false,
    isPrimal: true,
    generation: 3
  },
  {
    name: "Primal Kyogre",
    pokedexId: 382,
    types: ["Water"],
    attack: 353,
    defense: 268,
    stamina: 218,
    maxCp: 6672,
    pveScore: 100,
    dps: 59.8,
    bestFastMove: { name: "Waterfall", type: "Water" },
    bestChargedMove: { name: "Origin Pulse", type: "Water" },
    isMega: false,
    isShadow: false,
    isPrimal: true,
    generation: 3
  },

  // SHADOWS
  {
    name: "Shadow Mewtwo",
    pokedexId: 150,
    types: ["Psychic"],
    attack: 360,
    defense: 151,
    stamina: 214,
    maxCp: 4724,
    pveScore: 96,
    dps: 55.4,
    bestFastMove: { name: "Psycho Cut", type: "Psychic" },
    bestChargedMove: { name: "Psystrike", type: "Psychic" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Shadow Kyogre",
    pokedexId: 382,
    types: ["Water"],
    attack: 324,
    defense: 171,
    stamina: 205,
    maxCp: 4652,
    pveScore: 92,
    dps: 52.8,
    bestFastMove: { name: "Waterfall", type: "Water" },
    bestChargedMove: { name: "Origin Pulse", type: "Water" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Shadow Groudon",
    pokedexId: 383,
    types: ["Ground"],
    attack: 324,
    defense: 171,
    stamina: 205,
    maxCp: 4652,
    pveScore: 93,
    dps: 53.1,
    bestFastMove: { name: "Mud Shot", type: "Ground" },
    bestChargedMove: { name: "Precipice Blades", type: "Ground" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Shadow Rayquaza",
    pokedexId: 384,
    types: ["Dragon", "Flying"],
    attack: 341,
    defense: 142,
    stamina: 213,
    maxCp: 4335,
    pveScore: 94,
    dps: 54.6,
    bestFastMove: { name: "Dragon Tail", type: "Dragon" },
    bestChargedMove: { name: "Breaking Swipe", type: "Dragon" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Shadow Dialga",
    pokedexId: 483,
    types: ["Steel", "Dragon"],
    attack: 330,
    defense: 176,
    stamina: 205,
    maxCp: 4565,
    pveScore: 91,
    dps: 51.4,
    bestFastMove: { name: "Metal Claw", type: "Steel" },
    bestChargedMove: { name: "Iron Head", type: "Steel" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Shadow Palkia",
    pokedexId: 484,
    types: ["Water", "Dragon"],
    attack: 336,
    defense: 182,
    stamina: 189,
    maxCp: 4473,
    pveScore: 91,
    dps: 51.9,
    bestFastMove: { name: "Dragon Breath", type: "Dragon" },
    bestChargedMove: { name: "Draco Meteor", type: "Dragon" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Shadow Giratina (Origin)",
    pokedexId: 487,
    types: ["Ghost", "Dragon"],
    attack: 270,
    defense: 156,
    stamina: 284,
    maxCp: 4164,
    pveScore: 88,
    dps: 47.3,
    bestFastMove: { name: "Shadow Claw", type: "Ghost" },
    bestChargedMove: { name: "Shadow Force", type: "Ghost" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Shadow Heatran",
    pokedexId: 485,
    types: ["Fire", "Steel"],
    attack: 301,
    defense: 178,
    stamina: 209,
    maxCp: 4310,
    pveScore: 89,
    dps: 49.2,
    bestFastMove: { name: "Fire Spin", type: "Fire" },
    bestChargedMove: { name: "Magma Storm", type: "Fire" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Shadow Darkrai",
    pokedexId: 491,
    types: ["Dark"],
    attack: 342,
    defense: 165,
    stamina: 172,
    maxCp: 4242,
    pveScore: 90,
    dps: 52.1,
    bestFastMove: { name: "Snarl", type: "Dark" },
    bestChargedMove: { name: "Shadow Ball", type: "Ghost" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Shadow Raikou",
    pokedexId: 243,
    types: ["Electric"],
    attack: 289,
    defense: 162,
    stamina: 207,
    maxCp: 3904,
    pveScore: 88,
    dps: 48.7,
    bestFastMove: { name: "Thunder Shock", type: "Electric" },
    bestChargedMove: { name: "Wild Charge", type: "Electric" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 2
  },
  {
    name: "Shadow Entei",
    pokedexId: 244,
    types: ["Fire"],
    attack: 282,
    defense: 146,
    stamina: 251,
    maxCp: 3926,
    pveScore: 87,
    dps: 47.9,
    bestFastMove: { name: "Fire Fang", type: "Fire" },
    bestChargedMove: { name: "Overheat", type: "Fire" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 2
  },
  {
    name: "Shadow Moltres",
    pokedexId: 146,
    types: ["Fire", "Flying"],
    attack: 301,
    defense: 151,
    stamina: 207,
    maxCp: 3917,
    pveScore: 90,
    dps: 51.3,
    bestFastMove: { name: "Fire Spin", type: "Fire" },
    bestChargedMove: { name: "Overheat", type: "Fire" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Shadow Zapdos",
    pokedexId: 145,
    types: ["Electric", "Flying"],
    attack: 304,
    defense: 156,
    stamina: 207,
    maxCp: 3988,
    pveScore: 89,
    dps: 50.8,
    bestFastMove: { name: "Thunder Shock", type: "Electric" },
    bestChargedMove: { name: "Thunderbolt", type: "Electric" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Shadow Articuno",
    pokedexId: 144,
    types: ["Ice", "Flying"],
    attack: 230,
    defense: 202,
    stamina: 207,
    maxCp: 3450,
    pveScore: 76,
    dps: 38.6,
    bestFastMove: { name: "Frost Breath", type: "Ice" },
    bestChargedMove: { name: "Ice Beam", type: "Ice" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Shadow Tyranitar",
    pokedexId: 248,
    types: ["Rock", "Dark"],
    attack: 301,
    defense: 172,
    stamina: 225,
    maxCp: 4335,
    pveScore: 92,
    dps: 52.4,
    bestFastMove: { name: "Bite", type: "Dark" },
    bestChargedMove: { name: "Brutal Swing", type: "Dark" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 2
  },
  {
    name: "Shadow Metagross",
    pokedexId: 376,
    types: ["Steel", "Psychic"],
    attack: 308,
    defense: 190,
    stamina: 190,
    maxCp: 4286,
    pveScore: 93,
    dps: 53.6,
    bestFastMove: { name: "Bullet Punch", type: "Steel" },
    bestChargedMove: { name: "Meteor Mash", type: "Steel" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Shadow Salamence",
    pokedexId: 373,
    types: ["Dragon", "Flying"],
    attack: 332,
    defense: 140,
    stamina: 216,
    maxCp: 4287,
    pveScore: 92,
    dps: 53.2,
    bestFastMove: { name: "Dragon Tail", type: "Dragon" },
    bestChargedMove: { name: "Outrage", type: "Dragon" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Shadow Dragonite",
    pokedexId: 149,
    types: ["Dragon", "Flying"],
    attack: 316,
    defense: 165,
    stamina: 209,
    maxCp: 4287,
    pveScore: 91,
    dps: 51.7,
    bestFastMove: { name: "Dragon Tail", type: "Dragon" },
    bestChargedMove: { name: "Outrage", type: "Dragon" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Shadow Garchomp",
    pokedexId: 445,
    types: ["Dragon", "Ground"],
    attack: 313,
    defense: 161,
    stamina: 239,
    maxCp: 4479,
    pveScore: 92,
    dps: 52.6,
    bestFastMove: { name: "Dragon Tail", type: "Dragon" },
    bestChargedMove: { name: "Outrage", type: "Dragon" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Shadow Rhyperior",
    pokedexId: 464,
    types: ["Ground", "Rock"],
    attack: 289,
    defense: 158,
    stamina: 251,
    maxCp: 4221,
    pveScore: 91,
    dps: 51.3,
    bestFastMove: { name: "Mud-Slap", type: "Ground" },
    bestChargedMove: { name: "Rock Wrecker", type: "Rock" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Shadow Rampardos",
    pokedexId: 409,
    types: ["Rock"],
    attack: 354,
    defense: 91,
    stamina: 219,
    maxCp: 3728,
    pveScore: 91,
    dps: 54.8,
    bestFastMove: { name: "Smack Down", type: "Rock" },
    bestChargedMove: { name: "Rock Slide", type: "Rock" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Shadow Excadrill",
    pokedexId: 530,
    types: ["Ground", "Steel"],
    attack: 306,
    defense: 107,
    stamina: 242,
    maxCp: 3667,
    pveScore: 89,
    dps: 51.1,
    bestFastMove: { name: "Mud-Slap", type: "Ground" },
    bestChargedMove: { name: "Scorching Sands", type: "Ground" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 5
  },
  {
    name: "Shadow Mamoswine",
    pokedexId: 473,
    types: ["Ice", "Ground"],
    attack: 296,
    defense: 122,
    stamina: 242,
    maxCp: 3762,
    pveScore: 90,
    dps: 51.8,
    bestFastMove: { name: "Powder Snow", type: "Ice" },
    bestChargedMove: { name: "Avalanche", type: "Ice" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Shadow Chandelure",
    pokedexId: 609,
    types: ["Ghost", "Fire"],
    attack: 325,
    defense: 151,
    stamina: 155,
    maxCp: 3728,
    pveScore: 90,
    dps: 52.3,
    bestFastMove: { name: "Fire Spin", type: "Fire" },
    bestChargedMove: { name: "Shadow Ball", type: "Ghost" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 5
  },
  {
    name: "Shadow Blaziken",
    pokedexId: 257,
    types: ["Fire", "Fighting"],
    attack: 288,
    defense: 117,
    stamina: 190,
    maxCp: 3220,
    pveScore: 88,
    dps: 50.4,
    bestFastMove: { name: "Fire Spin", type: "Fire" },
    bestChargedMove: { name: "Blast Burn", type: "Fire" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Shadow Sceptile",
    pokedexId: 254,
    types: ["Grass"],
    attack: 268,
    defense: 141,
    stamina: 172,
    maxCp: 3117,
    pveScore: 86,
    dps: 48.7,
    bestFastMove: { name: "Bullet Seed", type: "Grass" },
    bestChargedMove: { name: "Frenzy Plant", type: "Grass" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Shadow Swampert",
    pokedexId: 260,
    types: ["Water", "Ground"],
    attack: 249,
    defense: 146,
    stamina: 225,
    maxCp: 3362,
    pveScore: 89,
    dps: 49.5,
    bestFastMove: { name: "Water Gun", type: "Water" },
    bestChargedMove: { name: "Hydro Cannon", type: "Water" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Shadow Machamp",
    pokedexId: 68,
    types: ["Fighting"],
    attack: 280,
    defense: 132,
    stamina: 207,
    maxCp: 3455,
    pveScore: 87,
    dps: 48.2,
    bestFastMove: { name: "Counter", type: "Fighting" },
    bestChargedMove: { name: "Dynamic Punch", type: "Fighting" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 1
  },
  {
    name: "Shadow Conkeldurr",
    pokedexId: 534,
    types: ["Fighting"],
    attack: 291,
    defense: 132,
    stamina: 233,
    maxCp: 3772,
    pveScore: 88,
    dps: 49.3,
    bestFastMove: { name: "Counter", type: "Fighting" },
    bestChargedMove: { name: "Dynamic Punch", type: "Fighting" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 5
  },
  {
    name: "Shadow Gardevoir",
    pokedexId: 282,
    types: ["Psychic", "Fairy"],
    attack: 284,
    defense: 161,
    stamina: 169,
    maxCp: 3497,
    pveScore: 88,
    dps: 48.6,
    bestFastMove: { name: "Charm", type: "Fairy" },
    bestChargedMove: { name: "Dazzling Gleam", type: "Fairy" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 3
  },
  {
    name: "Shadow Hydreigon",
    pokedexId: 635,
    types: ["Dark", "Dragon"],
    attack: 307,
    defense: 156,
    stamina: 210,
    maxCp: 4149,
    pveScore: 90,
    dps: 51.5,
    bestFastMove: { name: "Bite", type: "Dark" },
    bestChargedMove: { name: "Brutal Swing", type: "Dark" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 5
  },
  {
    name: "Shadow Weavile",
    pokedexId: 461,
    types: ["Dark", "Ice"],
    attack: 290,
    defense: 142,
    stamina: 172,
    maxCp: 3397,
    pveScore: 86,
    dps: 49.2,
    bestFastMove: { name: "Snarl", type: "Dark" },
    bestChargedMove: { name: "Avalanche", type: "Ice" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Shadow Honchkrow",
    pokedexId: 430,
    types: ["Dark", "Flying"],
    attack: 291,
    defense: 86,
    stamina: 225,
    maxCp: 3065,
    pveScore: 85,
    dps: 48.9,
    bestFastMove: { name: "Peck", type: "Flying" },
    bestChargedMove: { name: "Sky Attack", type: "Flying" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 4
  },
  {
    name: "Shadow Staraptor",
    pokedexId: 398,
    types: ["Normal", "Flying"],
    attack: 280,
    defense: 117,
    stamina: 198,
    maxCp: 3192,
    pveScore: 84,
    dps: 47.8,
    bestFastMove: { name: "Gust", type: "Flying" },
    bestChargedMove: { name: "Brave Bird", type: "Flying" },
    isShadow: true,
    isMega: false,
    isPrimal: false,
    generation: 4
  },

  // ZACIAN & ZAMAZENTA FORMS
  {
    name: "Zacian (Hero of Many Battles)",
    pokedexId: 888,
    types: ["Fairy"],
    attack: 254,
    defense: 236,
    stamina: 192,
    maxCp: 4329,
    pveScore: 78,
    dps: 42.1,
    bestFastMove: { name: "Snarl", type: "Dark" },
    bestChargedMove: { name: "Play Rough", type: "Fairy" },
    isShadow: false,
    isMega: false,
    isPrimal: false,
    generation: 8
  },
  {
    name: "Zacian (Crowned Sword)",
    pokedexId: 888,
    types: ["Fairy", "Steel"],
    attack: 332,
    defense: 240,
    stamina: 192,
    maxCp: 5549,
    pveScore: 94,
    dps: 54.2,
    bestFastMove: { name: "Metal Claw", type: "Steel" },
    bestChargedMove: { name: "Behemoth Blade", type: "Steel" },
    isShadow: false,
    isMega: false,
    isPrimal: false,
    generation: 8
  },
  {
    name: "Zamazenta (Hero of Many Battles)",
    pokedexId: 889,
    types: ["Fighting"],
    attack: 254,
    defense: 236,
    stamina: 192,
    maxCp: 4329,
    pveScore: 76,
    dps: 40.8,
    bestFastMove: { name: "Snarl", type: "Dark" },
    bestChargedMove: { name: "Close Combat", type: "Fighting" },
    isShadow: false,
    isMega: false,
    isPrimal: false,
    generation: 8
  },
  {
    name: "Zamazenta (Crowned Shield)",
    pokedexId: 889,
    types: ["Fighting", "Steel"],
    attack: 274,
    defense: 302,
    stamina: 192,
    maxCp: 5214,
    pveScore: 88,
    dps: 46.5,
    bestFastMove: { name: "Metal Claw", type: "Steel" },
    bestChargedMove: { name: "Behemoth Bash", type: "Steel" },
    isShadow: false,
    isMega: false,
    isPrimal: false,
    generation: 8
  }
];

// Apply updates
for (const item of allMegasAndShadows) {
  if (existingMap.has(item.name)) {
    const idx = list.findIndex(p => p.name === item.name);
    if (idx !== -1) {
      list[idx] = { ...list[idx], ...item };
    }
  } else {
    list.unshift(item);
  }
}

console.log('Final total count:', list.length);

const globalArrayStart = startIndex + arrayStart;
const globalArrayEnd = startIndex + arrayEnd;
const prefix = content.substring(0, globalArrayStart);
const suffix = content.substring(globalArrayEnd + 1);
const output = `${prefix}${JSON.stringify(list, null, 2)}${suffix}`;

fs.writeFileSync(rankingsFilePath, output, 'utf8');
console.log('Successfully updated pokemonRankings.ts');
