import { describe, it, expect } from 'vitest';
import { isPokemonReleasedInGo } from './pokemonReleaseHelper';
import type { PokemonRankData } from '../data/pokemonRankings';

describe('pokemonReleaseHelper', () => {
  it('correctly identifies released Pokemon in Pokemon GO (including Megas, Crowned forms, and Fusions)', () => {
    const bulbasaur = { pokedexId: 1, name: 'Bulbasaur', isMega: false } as PokemonRankData;
    const mewtwo = { pokedexId: 150, name: 'Mewtwo', isMega: false } as PokemonRankData;
    const megaMewtwoX = { pokedexId: 150, name: 'Mega Mewtwo X', isMega: true } as PokemonRankData;
    const megaMewtwoY = { pokedexId: 150, name: 'Mega Mewtwo Y', isMega: true } as PokemonRankData;
    const duskMane = { pokedexId: 800, name: 'Dusk Mane Necrozma', isMega: false } as PokemonRankData;
    const dawnWings = { pokedexId: 800, name: 'Dawn Wings Necrozma', isMega: false } as PokemonRankData;
    const blackKyurem = { pokedexId: 646, name: 'Black Kyurem', isMega: false } as PokemonRankData;
    const whiteKyurem = { pokedexId: 646, name: 'White Kyurem', isMega: false } as PokemonRankData;
    const zacianHero = { pokedexId: 888, name: 'Zacian (Hero of Many Battles)', isMega: false } as PokemonRankData;
    const zacianCrowned = { pokedexId: 888, name: 'Zacian (Crowned Sword)', isMega: false } as PokemonRankData;
    const zamazentaHero = { pokedexId: 889, name: 'Zamazenta (Hero of Many Battles)', isMega: false } as PokemonRankData;
    const zamazentaCrowned = { pokedexId: 889, name: 'Zamazenta (Crowned Shield)', isMega: false } as PokemonRankData;
    const grookey = { pokedexId: 810, name: 'Grookey', isMega: false } as PokemonRankData;
    const urshifu = { pokedexId: 892, name: 'Urshifu', isMega: false } as PokemonRankData;
    const toxtricity = { pokedexId: 849, name: 'Toxtricity', isMega: false } as PokemonRankData;
    const dragapult = { pokedexId: 887, name: 'Dragapult', isMega: false } as PokemonRankData;
    const overqwil = { pokedexId: 904, name: 'Overqwil', isMega: false } as PokemonRankData;
    const sneasler = { pokedexId: 903, name: 'Sneasler', isMega: false } as PokemonRankData;
    const sprigatito = { pokedexId: 906, name: 'Sprigatito', isMega: false } as PokemonRankData;
    const ceruledge = { pokedexId: 937, name: 'Ceruledge', isMega: false } as PokemonRankData;
    const armarouge = { pokedexId: 936, name: 'Armarouge', isMega: false } as PokemonRankData;
    const annihilape = { pokedexId: 979, name: 'Annihilape', isMega: false } as PokemonRankData;
    const kingambit = { pokedexId: 983, name: 'Kingambit', isMega: false } as PokemonRankData;
    const baxcalibur = { pokedexId: 998, name: 'Baxcalibur', isMega: false } as PokemonRankData;
    const gholdengo = { pokedexId: 1000, name: 'Gholdengo', isMega: false } as PokemonRankData;
    const volcanion = { pokedexId: 721, name: 'Volcanion', isMega: false } as PokemonRankData;
    const aegislash = { pokedexId: 681, name: 'Aegislash', isMega: false } as PokemonRankData;
    const zeraora = { pokedexId: 807, name: 'Zeraora', isMega: false } as PokemonRankData;

    expect(isPokemonReleasedInGo(bulbasaur)).toBe(true);
    expect(isPokemonReleasedInGo(mewtwo)).toBe(true);
    expect(isPokemonReleasedInGo(megaMewtwoX)).toBe(true);
    expect(isPokemonReleasedInGo(megaMewtwoY)).toBe(true);
    expect(isPokemonReleasedInGo(duskMane)).toBe(true);
    expect(isPokemonReleasedInGo(dawnWings)).toBe(true);
    expect(isPokemonReleasedInGo(blackKyurem)).toBe(true);
    expect(isPokemonReleasedInGo(whiteKyurem)).toBe(true);
    expect(isPokemonReleasedInGo(zacianHero)).toBe(true);
    expect(isPokemonReleasedInGo(zacianCrowned)).toBe(true);
    expect(isPokemonReleasedInGo(zamazentaHero)).toBe(true);
    expect(isPokemonReleasedInGo(zamazentaCrowned)).toBe(true);
    expect(isPokemonReleasedInGo(grookey)).toBe(true);
    expect(isPokemonReleasedInGo(urshifu)).toBe(true);
    expect(isPokemonReleasedInGo(toxtricity)).toBe(true);
    expect(isPokemonReleasedInGo(dragapult)).toBe(true);
    expect(isPokemonReleasedInGo(overqwil)).toBe(true);
    expect(isPokemonReleasedInGo(sneasler)).toBe(true);
    expect(isPokemonReleasedInGo(sprigatito)).toBe(true);
    expect(isPokemonReleasedInGo(ceruledge)).toBe(true);
    expect(isPokemonReleasedInGo(armarouge)).toBe(true);
    expect(isPokemonReleasedInGo(annihilape)).toBe(true);
    expect(isPokemonReleasedInGo(kingambit)).toBe(true);
    expect(isPokemonReleasedInGo(baxcalibur)).toBe(true);
    expect(isPokemonReleasedInGo(gholdengo)).toBe(true);
    expect(isPokemonReleasedInGo(volcanion)).toBe(true);
    expect(isPokemonReleasedInGo(aegislash)).toBe(true);
    expect(isPokemonReleasedInGo(zeraora)).toBe(true);
  });

  it('correctly identifies unreleased Pokemon, unreleased special forms and Paradox species', () => {
    const arceus = { pokedexId: 493, name: 'Arceus', isMega: false } as PokemonRankData;
    const phione = { pokedexId: 489, name: 'Phione', isMega: false } as PokemonRankData;
    const manaphy = { pokedexId: 490, name: 'Manaphy', isMega: false } as PokemonRankData;
    const mimikyu = { pokedexId: 778, name: 'Mimikyu', isMega: false } as PokemonRankData;
    const magearna = { pokedexId: 801, name: 'Magearna', isMega: false } as PokemonRankData;
    const calyrex = { pokedexId: 898, name: 'Calyrex', isMega: false } as PokemonRankData;
    const flutterMane = { pokedexId: 987, name: 'Flutter Mane', isMega: false } as PokemonRankData;
    const roaringMoon = { pokedexId: 1005, name: 'Roaring Moon', isMega: false } as PokemonRankData;
    const ironValiant = { pokedexId: 1006, name: 'Iron Valiant', isMega: false } as PokemonRankData;
    const greatTusk = { pokedexId: 984, name: 'Great Tusk', isMega: false } as PokemonRankData;
    const koraidon = { pokedexId: 1007, name: 'Koraidon', isMega: false } as PokemonRankData;
    const miraidon = { pokedexId: 1008, name: 'Miraidon', isMega: false } as PokemonRankData;
    const terapagos = { pokedexId: 1024, name: 'Terapagos', isMega: false } as PokemonRankData;
    const ultraNecrozma = { pokedexId: 800, name: 'Ultra Necrozma', isMega: false } as PokemonRankData;
    const eternamax = { pokedexId: 890, name: 'Eternatus (Eternamax)', isMega: false } as PokemonRankData;
    const zenModeDarmanitan = { pokedexId: 555, name: 'Darmanitan (Zen Mode)', isMega: false } as PokemonRankData;
    const zenModeGalarianDarmanitan = { pokedexId: 555, name: 'Galarian Darmanitan (Zen Mode)', isMega: false } as PokemonRankData;
    const shadowZenModeGalarian = { pokedexId: 555, name: 'Shadow Galarian Darmanitan (Zen Mode)', isShadow: true } as PokemonRankData;

    expect(isPokemonReleasedInGo(arceus)).toBe(false);
    expect(isPokemonReleasedInGo(phione)).toBe(false);
    expect(isPokemonReleasedInGo(manaphy)).toBe(false);
    expect(isPokemonReleasedInGo(mimikyu)).toBe(false);
    expect(isPokemonReleasedInGo(magearna)).toBe(false);
    expect(isPokemonReleasedInGo(calyrex)).toBe(false);
    expect(isPokemonReleasedInGo(flutterMane)).toBe(false);
    expect(isPokemonReleasedInGo(roaringMoon)).toBe(false);
    expect(isPokemonReleasedInGo(ironValiant)).toBe(false);
    expect(isPokemonReleasedInGo(greatTusk)).toBe(false);
    expect(isPokemonReleasedInGo(koraidon)).toBe(false);
    expect(isPokemonReleasedInGo(miraidon)).toBe(false);
    expect(isPokemonReleasedInGo(terapagos)).toBe(false);
    expect(isPokemonReleasedInGo(ultraNecrozma)).toBe(false);
    expect(isPokemonReleasedInGo(eternamax)).toBe(false);
    expect(isPokemonReleasedInGo(zenModeDarmanitan)).toBe(false);
    expect(isPokemonReleasedInGo(zenModeGalarianDarmanitan)).toBe(false);
    expect(isPokemonReleasedInGo(shadowZenModeGalarian)).toBe(false);
  });

  it('correctly distinguishes released shadows (including Regigigas, Reshiram) from unreleased shadows', () => {
    // Released shadows (Kanto birds, Mewtwo, Johto beasts, etc.)
    const shadowMewtwo = { pokedexId: 150, name: 'Shadow Mewtwo', isShadow: true } as PokemonRankData;
    const shadowArticuno = { pokedexId: 144, name: 'Shadow Articuno', isShadow: true } as PokemonRankData;
    const shadowZapdos = { pokedexId: 145, name: 'Shadow Zapdos', isShadow: true } as PokemonRankData;
    const shadowMoltres = { pokedexId: 146, name: 'Shadow Moltres', isShadow: true } as PokemonRankData;
    const shadowHoOh = { pokedexId: 250, name: 'Shadow Ho-Oh', isShadow: true } as PokemonRankData;
    const shadowMachamp = { pokedexId: 68, name: 'Shadow Machamp', isShadow: true } as PokemonRankData;
    const shadowGarchomp = { pokedexId: 445, name: 'Shadow Garchomp', isShadow: true } as PokemonRankData;
    const shadowRegigigas = { pokedexId: 486, name: 'Shadow Regigigas', isShadow: true } as PokemonRankData;
    const shadowReshiram = { pokedexId: 643, name: 'Shadow Reshiram', isShadow: true } as PokemonRankData;
    const shadowDialga = { pokedexId: 483, name: 'Shadow Dialga', isShadow: true } as PokemonRankData;
    const shadowPalkia = { pokedexId: 484, name: 'Shadow Palkia', isShadow: true } as PokemonRankData;
    const shadowHeatran = { pokedexId: 485, name: 'Shadow Heatran', isShadow: true } as PokemonRankData;
    const shadowCresselia = { pokedexId: 488, name: 'Shadow Cresselia', isShadow: true } as PokemonRankData;

    expect(isPokemonReleasedInGo(shadowMewtwo)).toBe(true);
    expect(isPokemonReleasedInGo(shadowArticuno)).toBe(true);
    expect(isPokemonReleasedInGo(shadowZapdos)).toBe(true);
    expect(isPokemonReleasedInGo(shadowMoltres)).toBe(true);
    expect(isPokemonReleasedInGo(shadowHoOh)).toBe(true);
    expect(isPokemonReleasedInGo(shadowMachamp)).toBe(true);
    expect(isPokemonReleasedInGo(shadowGarchomp)).toBe(true);
    expect(isPokemonReleasedInGo(shadowRegigigas)).toBe(true);
    expect(isPokemonReleasedInGo(shadowReshiram)).toBe(true);
    expect(isPokemonReleasedInGo(shadowDialga)).toBe(true);
    expect(isPokemonReleasedInGo(shadowPalkia)).toBe(true);
    expect(isPokemonReleasedInGo(shadowHeatran)).toBe(true);
    expect(isPokemonReleasedInGo(shadowCresselia)).toBe(true);

    // Unreleased shadows (Shadow Rayquaza, Shadow Galarian Birds, Shadow Gen 8/9)
    const shadowRayquaza = { pokedexId: 384, name: 'Shadow Rayquaza', isShadow: true } as PokemonRankData;
    const shadowGalarianArticuno = { pokedexId: 144, name: 'Shadow Galarian Articuno', isShadow: true } as PokemonRankData;
    const shadowGalarianZapdos = { pokedexId: 145, name: 'Shadow Galarian Zapdos', isShadow: true } as PokemonRankData;
    const shadowGalarianMoltres = { pokedexId: 146, name: 'Shadow Galarian Moltres', isShadow: true } as PokemonRankData;
    const shadowBaxcalibur = { pokedexId: 998, name: 'Shadow Baxcalibur', isShadow: true } as PokemonRankData;
    const shadowEternatus = { pokedexId: 890, name: 'Shadow Eternatus', isShadow: true } as PokemonRankData;
    const shadowZacian = { pokedexId: 888, name: 'Shadow Zacian', isShadow: true } as PokemonRankData;
    const shadowZamazenta = { pokedexId: 889, name: 'Shadow Zamazenta', isShadow: true } as PokemonRankData;
    const shadowGholdengo = { pokedexId: 1000, name: 'Shadow Gholdengo', isShadow: true } as PokemonRankData;
    const shadowDragapult = { pokedexId: 887, name: 'Shadow Dragapult', isShadow: true } as PokemonRankData;
    const shadowKyurem = { pokedexId: 646, name: 'Shadow Kyurem', isShadow: true } as PokemonRankData;
    const shadowZekrom = { pokedexId: 644, name: 'Shadow Zekrom', isShadow: true } as PokemonRankData;

    expect(isPokemonReleasedInGo(shadowRayquaza)).toBe(false);
    expect(isPokemonReleasedInGo(shadowGalarianArticuno)).toBe(false);
    expect(isPokemonReleasedInGo(shadowGalarianZapdos)).toBe(false);
    expect(isPokemonReleasedInGo(shadowGalarianMoltres)).toBe(false);
    expect(isPokemonReleasedInGo(shadowBaxcalibur)).toBe(false);
    expect(isPokemonReleasedInGo(shadowEternatus)).toBe(false);
    expect(isPokemonReleasedInGo(shadowZacian)).toBe(false);
    expect(isPokemonReleasedInGo(shadowZamazenta)).toBe(false);
    expect(isPokemonReleasedInGo(shadowGholdengo)).toBe(false);
    expect(isPokemonReleasedInGo(shadowDragapult)).toBe(false);
    expect(isPokemonReleasedInGo(shadowKyurem)).toBe(false);
    expect(isPokemonReleasedInGo(shadowZekrom)).toBe(false);
  });
});
